HW13. Setting up owner authorization.

diff --git a/hw13/mvnw b/hw13/mvnw
--- a/hw13/mvnw
+++ b/hw13/mvnw
@@ -152,7 +152,7 @@ fi
 
 if [ ! -x "$JAVACMD" ] ; then
   echo "Error: JAVA_HOME is not defined correctly." >&2
-  echo "  We cannot execute $JAVACMD" >&2
+  echo "  We cannot grantAccess $JAVACMD" >&2
   exit 1
 fi
 
